// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvjcpyijakskshhfyrkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2amNweWlqYWtza3NoaGZ5cmt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDIzOTUsImV4cCI6MjA2ODUxODM5NX0.1Ksl43raaYmJBADgaj8Ts75LHNAwYZJ3ivuLk9VX9Ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});